# Generated by Django 4.2.5 on 2023-09-21 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('especie', models.CharField(max_length=50, verbose_name='Especie')),
                ('raza', models.CharField(blank=True, max_length=50, null=True, verbose_name='Raza')),
                ('peso', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha creación')),
            ],
        ),
        migrations.CreateModel(
            name='animalAdopcion',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='furever.animal')),
                ('vacunas_completas', models.BooleanField(verbose_name='Vacunas completas')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('necesidades_esp', models.TextField(blank=True, null=True, verbose_name='Necesidades especiales')),
            ],
            bases=('furever.animal',),
        ),
        migrations.CreateModel(
            name='AnimalVenta',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='furever.animal')),
                ('sanidad', models.BooleanField(verbose_name='Sanidad')),
                ('uniformidad', models.BooleanField(verbose_name='Uniformidad')),
                ('trazada', models.BooleanField(verbose_name='Trazada')),
                ('marca_liquida', models.BooleanField(verbose_name='Marca líquida')),
                ('garrapata', models.BooleanField(verbose_name='Garrapata')),
                ('mio_mio', models.BooleanField(verbose_name='Mio Mio')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
            ],
            bases=('furever.animal',),
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Oferente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=50, verbose_name='Provincia')),
                ('empresa_fundacion', models.CharField(max_length=100, verbose_name='Empresa/Fundación')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='furever.userapp')),
            ],
        ),
        migrations.CreateModel(
            name='Interesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('ninos', models.BooleanField(verbose_name='Niños')),
                ('tipo_hogar', models.TextField(blank=True, null=True, verbose_name='Tipo de hogar')),
                ('animales_previos', models.BooleanField(verbose_name='Animales Previos')),
                ('animales_actuales', models.BooleanField(verbose_name='Animales Actuales')),
                ('horarios', models.TextField(blank=True, null=True, verbose_name='Horarios')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='furever.userapp')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='user_pics/')),
                ('interesado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='furever.interesado')),
            ],
        ),
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.FileField(upload_to='user_docs/')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('oferente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='furever.oferente')),
            ],
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EE', 'En espera'), ('AC', 'Aceptado'), ('RZ', 'Rechazado')], default='EE', max_length=20)),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha creación')),
                ('interesado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='furever.interesado')),
                ('oferente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='furever.oferente')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='furever.animaladopcion')),
            ],
        ),
    ]
