# Generated by Django 4.1.6 on 2023-10-02 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furever', '0002_alter_animal_especie_alter_animalventa_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='peso',
            field=models.CharField(max_length=50, verbose_name='Peso'),
        ),
    ]
