# Generated by Django 4.2.5 on 2023-10-04 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furever', '0004_animal_oferente_alter_conexion_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='oferente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='furever.oferente'),
        ),
    ]
