# Generated by Django 4.2.5 on 2023-10-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furever', '0006_foto_animal_alter_foto_interesado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conexion',
            name='oferente',
        ),
    ]
