# Generated by Django 4.1.6 on 2023-10-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furever', '0007_remove_conexion_oferente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='especie',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='raza',
        ),
        migrations.AddField(
            model_name='animal',
            name='genero',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='P', max_length=20),
        ),
        migrations.AddField(
            model_name='animaladopcion',
            name='especie',
            field=models.CharField(choices=[('P', 'Perro'), ('G', 'Gato'), ('C', 'Conejo'), ('T', 'Tortuga'), ('S', 'Serpiente'), ('G', 'De granja'), ('O', 'Otros')], default='P', max_length=20),
        ),
        migrations.AddField(
            model_name='animaladopcion',
            name='raza',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Raza'),
        ),
        migrations.AddField(
            model_name='animalventa',
            name='especie',
            field=models.CharField(choices=[('V', 'Vaca'), ('G', 'Gallina'), ('C', 'Cerdo'), ('C', 'Caballos'), ('O', 'Otros')], default='P', max_length=20),
        ),
        migrations.AddField(
            model_name='animalventa',
            name='raza',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Raza'),
        ),
    ]
