# Generated by Django 4.1.6 on 2023-10-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furever', '0008_remove_animal_especie_remove_animal_raza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Link a foto'),
        ),
    ]
