# Generated by Django 4.1.6 on 2023-10-12 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furever', '0009_alter_foto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='doc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Link a documentacion'),
        ),
    ]
