# Generated by Django 4.2.5 on 2023-10-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furever', '0010_alter_documentacion_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='doc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link a documentacion'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Link a foto'),
        ),
    ]
