# Generated by Django 4.2.5 on 2023-10-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furever', '0012_alter_interesado_animales_actuales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conexion',
            name='tipo',
            field=models.CharField(choices=[('P', 'Positiva'), ('N', 'Negativa')], default='P', max_length=20),
        ),
    ]
