# Generated by Django 4.2.5 on 2023-10-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furever', '0014_alter_animal_oferente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaladopcion',
            name='especie',
            field=models.CharField(choices=[('P', 'Perro'), ('G', 'Gato'), ('C', 'Conejo'), ('T', 'Tortuga'), ('S', 'Serpiente'), ('DG', 'De granja'), ('O', 'Otros')], default='P', max_length=20),
        ),
    ]
