# Generated by Django 4.2.5 on 2023-11-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furever', '0015_alter_animaladopcion_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferente',
            name='empresa_fundacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa/Fundación'),
        ),
        migrations.AlterField(
            model_name='oferente',
            name='provincia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Provincia'),
        ),
    ]
